name: AngularApp$(Date:yyyyMMdd)$(Rev:.r)
trigger:
- main
pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:

- task: UseNode@1
  inputs:
    version: '18.14.0'
  displayName: 'Install Node.js'

- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
      npm | "$(Agent.OS)"
    path: $(Pipeline.Workspace)/.npm
  displayName: 'Cache npm'

- task: Npm@1
  displayName: 'Install Angular CLI and Dependencies'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -g @angular/cli@13.2.5 && npm install file:custom-angular-lib.tgz --legacy-peer-deps'

- task: AngularCLI@0
  displayName: 'Build Angular App'
  inputs:
    command: 'build'
    configuration: $(buildConfiguration)
    outputPath: '$(System.DefaultWorkingDirectory)/dist'
    baseHref: '/'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/dist'
    artifactName: 'angular-app'
   