name: angular-app-build-$(Date:yyyyMMdd)$(Rev:.r)
trigger:
- main
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'production'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install Angular CLI and Dependencies'

- script: |
    ng build --configuration=$(buildConfiguration)
  displayName: 'Build Angular App'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/dist' 
    artifactName: 'angular-app'
