name: AngularApp$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  - main
pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x' # Adjust Node.js version as needed
    displayName: 'Install Node.js'

  - script: |
      npm install @angular/cli
    displayName: 'Install Angular CLI'

  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      ng build --configuration=$(buildConfiguration)
    displayName: 'Build Angular App'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
      artifactName: 'angular-app'
