# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: AngularApp_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
- main

pool:
  name: default

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install Angular CLI and Dependencies'

- script: |
    ng build --configuration=$(buildConfiguration)
  displayName: 'Build Angular App'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/dist' 
    artifactName: 'angular-app'
